/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author Dian Arifia
 */
public class Laporan extends javax.swing.JFrame {
    String kuliah1;
    String kuliah2;
    String me1;
    String me2;
    String rangkum1, rangkum2;
    String dead1, dead2;
    String kondisilain;
    String lainlainolahraga;
    /**
     * Creates new form Kesbug
     */
    public Laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jSpinner1 = new javax.swing.JSpinner();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        npm = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        KondisiFisik = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Aktivitas = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sehat = new javax.swing.JCheckBox();
        demam = new javax.swing.JCheckBox();
        batuk = new javax.swing.JCheckBox();
        sesak = new javax.swing.JCheckBox();
        hidung = new javax.swing.JCheckBox();
        sakit = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        membatasi = new javax.swing.JCheckBox();
        tidak = new javax.swing.JCheckBox();
        menjaga = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        pushup = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        situp = new javax.swing.JSpinner();
        jogging = new javax.swing.JSpinner();
        pilek = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        matkul2 = new javax.swing.JComboBox<>();
        deadline2 = new javax.swing.JTextField();
        matkul1 = new javax.swing.JComboBox<>();
        deadline1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        media1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rangkuman1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        media2 = new javax.swing.JTextField();
        rangkuman2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        matkul11 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        KondisiFisik1 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jogging1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        situp1 = new javax.swing.JTextField();
        matkul21 = new javax.swing.JTextField();
        media11 = new javax.swing.JTextField();
        rangkuman21 = new javax.swing.JTextField();
        pushup1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        rangkuman11 = new javax.swing.JTextField();
        deadline21 = new javax.swing.JTextField();
        media21 = new javax.swing.JTextField();
        deadline11 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Aktivitas1 = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        lainlain1 = new javax.swing.JCheckBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        lainlain2 = new javax.swing.JTextArea();
        lainlainol1 = new javax.swing.JTextField();
        lainlainol2 = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        jScrollPane1.setViewportView(jEditorPane1);

        jFormattedTextField1.setText("jFormattedTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Mata Kuliah");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField5");

        jTextField8.setText("jTextField5");

        jTextField9.setText("jTextField5");

        jTextField11.setText("jTextField5");

        jTextField12.setText("jTextField5");

        jTextField13.setText("jTextField5");

        jLabel16.setText("NPM");

        jTextField14.setText("jTextField5");

        npm.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                npmAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        npm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npmActionPerformed(evt);
            }
        });

        jLabel17.setText("jLabel10");

        jLabel18.setText("Kondisi Fisik");

        jLabel19.setText("Rangkuman");

        KondisiFisik.setColumns(20);
        KondisiFisik.setRows(5);
        jScrollPane2.setViewportView(KondisiFisik);

        jLabel20.setText("Deadline");

        Aktivitas.setColumns(20);
        Aktivitas.setRows(5);
        jScrollPane3.setViewportView(Aktivitas);

        jLabel21.setText("Aktivitas");

        jLabel22.setText("Push Up");

        jLabel23.setText("Sit Up");

        jLabel24.setText("Jogging / Senam ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kesehatan dan Kebugaran");

        jLabel2.setText("Kondisi Fisik");

        sehat.setText("Sehat bugar");
        sehat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sehatStateChanged(evt);
            }
        });
        sehat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehatActionPerformed(evt);
            }
        });

        demam.setText("Demam");
        demam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demamActionPerformed(evt);
            }
        });

        batuk.setText("Batuk");
        batuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batukActionPerformed(evt);
            }
        });

        sesak.setText("Sesak nafas");
        sesak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesakActionPerformed(evt);
            }
        });

        hidung.setText("Hidung tidak dapat membau");
        hidung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidungActionPerformed(evt);
            }
        });

        sakit.setText("Sakit tenggorokan");
        sakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sakitActionPerformed(evt);
            }
        });

        jLabel3.setText("Aktivitas");

        membatasi.setText("Membatasi keluar rumah");
        membatasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membatasiActionPerformed(evt);
            }
        });

        tidak.setText("Tidak mengunjungi kerabat yang sakit");
        tidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakActionPerformed(evt);
            }
        });

        menjaga.setText("Menjaga jarak yang aman saat berinteraksi");
        menjaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menjagaActionPerformed(evt);
            }
        });

        jLabel4.setText("Push Up");

        jLabel5.setText("Sit Up");

        pilek.setText("Pilek");
        pilek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilekActionPerformed(evt);
            }
        });

        jLabel7.setText("kali");

        jLabel8.setText("kali");

        jLabel9.setText("menit");

        matkul2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Algoritma Pemrograman Lanjut", "Infrastruktur Kunci Publik", "Keamanan Siber", "Keamanan Jaringan", "Pemrograman Berorientasi Obek", "Kerawanan Perangkat Lunak" }));
        matkul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkul2ActionPerformed(evt);
            }
        });

        deadline2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadline2ActionPerformed(evt);
            }
        });

        matkul1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Ada", "Algoritma Pemrograman Lanjut", "Infrastruktur Kunci Publik", "Keamanan Siber", "Keamanan Jaringan", "Pemrograman Berorientasi Obek", "Kerawanan Perangkat Lunak" }));
        matkul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkul1ActionPerformed(evt);
            }
        });

        deadline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadline1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Mata kuliah");

        jLabel11.setText("Rangkuman");

        media1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                media1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Media");

        rangkuman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangkuman1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Deadline");

        media2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                media2ActionPerformed(evt);
            }
        });

        rangkuman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangkuman2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Perkuliahan Jarak Jauh");

        KondisiFisik1.setColumns(20);
        KondisiFisik1.setRows(5);
        jScrollPane4.setViewportView(KondisiFisik1);

        jLabel26.setText("Deadline");

        jLabel27.setText("Aktivitas");

        matkul21.setText("jTextField5");

        rangkuman21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangkuman21ActionPerformed(evt);
            }
        });

        pushup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushup1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Rangkuman");

        rangkuman11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangkuman11ActionPerformed(evt);
            }
        });

        jLabel29.setText("Kondisi Fisik");

        jLabel30.setText("jLabel10");

        jLabel31.setText("Push Up");

        Aktivitas1.setColumns(20);
        Aktivitas1.setRows(5);
        jScrollPane5.setViewportView(Aktivitas1);

        jLabel32.setText("Sit Up");

        jLabel33.setText("Mata Kuliah");

        simpan.setText("Simpan");
        simpan.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                simpanStateChanged(evt);
            }
        });
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        lainlain1.setText("Lain - lain");
        lainlain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lainlain1ActionPerformed(evt);
            }
        });

        lainlain2.setColumns(20);
        lainlain2.setRows(5);
        jScrollPane6.setViewportView(lainlain2);

        lainlainol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lainlainol1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(matkul21, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(media21, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rangkuman21, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(matkul11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel33))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(media11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(rangkuman11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deadline11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deadline21, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26)
                                        .addGap(87, 87, 87))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31)
                                    .addComponent(lainlainol2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pushup1)
                                        .addComponent(situp1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jogging1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pushup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(situp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jogging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))
                                    .addComponent(lainlainol1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sehat)
                                                .addGap(18, 18, 18)
                                                .addComponent(pilek))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(demam)
                                                    .addComponent(batuk))
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sesak)
                                                    .addComponent(hidung))))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lainlain1)
                                            .addComponent(sakit)))
                                    .addComponent(membatasi)
                                    .addComponent(jLabel3)
                                    .addComponent(menjaga)
                                    .addComponent(tidak))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(matkul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(media1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rangkuman1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(deadline1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(matkul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(media2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rangkuman2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(deadline2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(simpan)))))
                        .addGap(48, 127, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sakit)
                            .addComponent(pilek)
                            .addComponent(sehat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(demam)
                            .addComponent(sesak)
                            .addComponent(lainlain1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batuk)
                            .addComponent(hidung)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matkul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(media1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rangkuman1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deadline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matkul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(media2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rangkuman2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deadline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpan))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(membatasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tidak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menjaga))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(situp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lainlainol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jogging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))))
                            .addGap(5, 5, 5)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pushup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jogging1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lainlainol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pushup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(situp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel33)
                                .addComponent(jLabel30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(matkul11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(media11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rangkuman11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(matkul21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(media21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rangkuman21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deadline11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deadline21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel26))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void demamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demamActionPerformed
        // TODO add your handling code here:
        if (demam.isSelected()) {
            sehat.setSelected(false);
        }
    }//GEN-LAST:event_demamActionPerformed

    private void sehatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sehatStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sehatStateChanged

    private void sehatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehatActionPerformed
        // TODO add your handling code here:
        if (sehat.isSelected()) {
            sehat.setSelected(true);
            demam.setSelected(false);
            batuk.setSelected(false);
            pilek.setSelected(false);
            sesak.setSelected(false);
            hidung.setSelected(false);
            sakit.setSelected(false);
        }
    }//GEN-LAST:event_sehatActionPerformed

    private void batukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batukActionPerformed
        // TODO add your handling code here:
        if (batuk.isSelected()) {
            sehat.setSelected(false);
            batuk.setSelected(true);
        }
    }//GEN-LAST:event_batukActionPerformed

    private void pilekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilekActionPerformed
        // TODO add your handling code here:
        if (pilek.isSelected()) {
            sehat.setSelected(false);
            pilek.setSelected(true);
        }
        
    }//GEN-LAST:event_pilekActionPerformed

    private void sesakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesakActionPerformed
        // TODO add your handling code here:
        if (sesak.isSelected()) {
            sehat.setSelected(false);
            sesak.setSelected(true);
        }
    }//GEN-LAST:event_sesakActionPerformed

    private void hidungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidungActionPerformed
        // TODO add your handling code here:
        if (hidung.isSelected()) {
            sehat.setSelected(false);
            hidung.setSelected(true);
        }
    }//GEN-LAST:event_hidungActionPerformed

    private void sakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sakitActionPerformed
        // TODO add your handling code here:
        if (sakit.isSelected()) {
            sehat.setSelected(false);
            sakit.setSelected(true);
        }
    }//GEN-LAST:event_sakitActionPerformed

    private void membatasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membatasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membatasiActionPerformed

    private void tidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakActionPerformed

    }//GEN-LAST:event_tidakActionPerformed

    private void menjagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menjagaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menjagaActionPerformed

    private void matkul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkul2ActionPerformed
        // TODO add your handling code here:
        
        if(kuliah1=="Tidak Ada")    {
            kuliah2="Tidak Ada";
    }
        else
            kuliah2 = matkul2.getSelectedItem().toString();
    }//GEN-LAST:event_matkul2ActionPerformed

    private void deadline2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadline2ActionPerformed
        // TODO add your handling code here:
        dead2 = deadline1.getText();
    }//GEN-LAST:event_deadline2ActionPerformed

    private void matkul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkul1ActionPerformed
        // TODO add your handling code here:

        kuliah1 = matkul1.getSelectedItem().toString();
    }//GEN-LAST:event_matkul1ActionPerformed

    private void deadline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadline1ActionPerformed
        // TODO add your handling code here:
        dead1 = deadline1.getText();
    }//GEN-LAST:event_deadline1ActionPerformed

    private void media1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_media1ActionPerformed
        // TODO add your handling code here:
        
            
    }//GEN-LAST:event_media1ActionPerformed

    private void rangkuman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangkuman1ActionPerformed
        // TODO add your handling code here:
        
            rangkum1 = rangkuman1.getText();
            
        
    }//GEN-LAST:event_rangkuman1ActionPerformed

    private void media2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_media2ActionPerformed
        // TODO add your handling code here:
        if (kuliah1=="Tidak ada")
            me2 = "";
        else
        me2 = media2.getText();
    }//GEN-LAST:event_media2ActionPerformed

    private void rangkuman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangkuman2ActionPerformed
        // TODO add your handling code here:
        if (kuliah1=="Tidak ada")
            rangkum2 = "";
        else
        rangkum2 = rangkuman2.getText();
    }//GEN-LAST:event_rangkuman2ActionPerformed

    private void npmAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_npmAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_npmAncestorAdded

    private void npmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npmActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_npmActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        if(sehat.isSelected())  {
            KondisiFisik1.append("Sehat");
        }
        if(demam.isSelected())  {
            KondisiFisik1.append("Demam\n");
        }
        if(batuk.isSelected())  {
            KondisiFisik1.append("Batuk\n");
        }
        if(pilek.isSelected())  {
            KondisiFisik1.append("Pilek\n");
        }
        if(sesak.isSelected())  {
            KondisiFisik1.append("Sesak nafas\n");
        }
        if(hidung.isSelected()) {
            KondisiFisik1.append("Hidung tidak dapat mengendus\n");
        }
        if(sakit.isSelected())  {
            KondisiFisik1.append("Sakit tenggorokan\n");
        }
        if(lainlain1.isSelected())  {
            kondisilain = lainlain2.getText();
            KondisiFisik1.append(kondisilain);
        }
        
        
        if (membatasi.isSelected()) {
            Aktivitas1.append("Membatasi keluar rumah\n");
        }
        if(tidak.isSelected())  {
            Aktivitas1.append("Tidak mengunjungi kerabat yang sakit\n");
        }
        if(menjaga.isSelected())    {
            Aktivitas1.append("Menjaga jarak aman saat berinteraksi dengan orang\n");
        }
        
        Integer push = (Integer) pushup.getValue();
        String p = push.toString();
        pushup1.setText(p);
        
        Integer sit = (Integer) situp.getValue();
        String s = sit.toString();
        situp1.setText(s);
        
        Integer jog = (Integer) jogging.getValue();
        String j = jog.toString();
        jogging1.setText(j);

        lainlainolahraga = lainlainol1.getText();
        lainlainol2.setText(lainlainolahraga);
        
        matkul11.setText(kuliah1);
        
        if(kuliah1=="Tidak Ada")
        {
            kuliah2="";
            me1="";
            me2="";
            rangkum1="";
            rangkum2="";
            dead1="";
            dead2="";
        }
        else
        {
        matkul21.setText(kuliah2);
        me1 = media1.getText();
        media11.setText(me1);
        me2 = media2.getText();
        media21.setText(me2);
        rangkum1 = rangkuman1.getText();
        rangkuman11.setText(rangkum1);
        rangkum2 = rangkuman2.getText();
        rangkuman21.setText(rangkum2);
        dead1 = deadline1.getText();
        deadline11.setText(dead1);
        dead2 = deadline2.getText();
        deadline21.setText(dead2);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void simpanStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_simpanStateChanged
        // TODO add your handling code here:
 
        
        
        
    }//GEN-LAST:event_simpanStateChanged

    private void pushup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pushup1ActionPerformed

    private void rangkuman11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangkuman11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangkuman11ActionPerformed

    private void rangkuman21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangkuman21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangkuman21ActionPerformed

    private void lainlain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lainlain1ActionPerformed
        // TODO add your handling code here:
        if (lainlain1.isSelected()) {
            sehat.setSelected(false);
            lainlain1.setSelected(true);
        }
        
    }//GEN-LAST:event_lainlain1ActionPerformed

    private void lainlainol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lainlainol1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lainlainol1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Aktivitas;
    private javax.swing.JTextArea Aktivitas1;
    private javax.swing.JTextArea KondisiFisik;
    private javax.swing.JTextArea KondisiFisik1;
    private javax.swing.JCheckBox batuk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JTextField deadline1;
    private javax.swing.JTextField deadline11;
    private javax.swing.JTextField deadline2;
    private javax.swing.JTextField deadline21;
    private javax.swing.JCheckBox demam;
    private javax.swing.JCheckBox hidung;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JSpinner jogging;
    private javax.swing.JTextField jogging1;
    private javax.swing.JCheckBox lainlain1;
    private javax.swing.JTextArea lainlain2;
    private javax.swing.JTextField lainlainol1;
    private javax.swing.JTextField lainlainol2;
    private javax.swing.JComboBox<String> matkul1;
    private javax.swing.JTextField matkul11;
    private javax.swing.JComboBox<String> matkul2;
    private javax.swing.JTextField matkul21;
    private javax.swing.JTextField media1;
    private javax.swing.JTextField media11;
    private javax.swing.JTextField media2;
    private javax.swing.JTextField media21;
    private javax.swing.JCheckBox membatasi;
    private javax.swing.JCheckBox menjaga;
    private javax.swing.JTextField npm;
    private javax.swing.JCheckBox pilek;
    private javax.swing.JSpinner pushup;
    private javax.swing.JTextField pushup1;
    private javax.swing.JTextField rangkuman1;
    private javax.swing.JTextField rangkuman11;
    private javax.swing.JTextField rangkuman2;
    private javax.swing.JTextField rangkuman21;
    private javax.swing.JCheckBox sakit;
    private javax.swing.JCheckBox sehat;
    private javax.swing.JCheckBox sesak;
    private javax.swing.JButton simpan;
    private javax.swing.JSpinner situp;
    private javax.swing.JTextField situp1;
    private javax.swing.JCheckBox tidak;
    // End of variables declaration//GEN-END:variables
}
